### PR TITLE
Port C code to Rust

### PR DESCRIPTION
**Pull request by ids1024**
There are a couple advantages to this:
- There is somewhat less danger of making an incorrect system call, since `redox_syscall` can be used. Thus an issue like the one fixed in #4 would have been caught.
- Non-trivial code implemented in Rust does not need to be duplicated. For instance, `gethostbyname()` could use the host name resolution code in Redox's libstd. This eliminates the need to rewrite the code, and it is generally better to have only one implementation for consistency.

Disadvantages:
- Adds some bloat to libc.
- For the simple functions that are just a system call, the Rust implementation is more complicated and uglier, since it has to convert C types to rust types.

I think if this is done, either all the C code in `sys/redox` should be ported to Rust, or only things like `gethostbyname()`, that substantially benefit, should.

Thoughts?

### CODE REVIEW

**Comment by jackpot51** [comment]
Pretty cool. Try to avoid allocation of cstr by using strlen to make a u8 slice. Paths do not need to be UTF-8

**Comment by ids1024** [comment]
I think the solution here is to replace `&str` with `AsRef<[u8]>` in the syscall crate.

**Comment by ids1024** [comment]
@jackpot51 So do you think it would be good to replace everything in `sys/redox` with Rust code (which shouldn't be too hard; there isn't much code there now.)?

This does seem to increase binary size, but `#[no_std]` would address that.

**Comment by jackpot51** [comment]
Yeah, I think it would be if it is easy

**Comment by jackpot51** [comment]
Glad to see this coming along! Looks good!

**Comment by ids1024** [comment]
This is largely done, pending the merge of the PR linked above and changes here to match (trivial). And perhaps some testing.

**Comment by ids1024** [comment]
This should be ready to merge. If you get build errors related to libtest, install the git version of `xargo`.

The PR in the `libc` repo also needs to be merged (and the submodule updated, of course). A new version of `redox_syscall` should be pushed to crates.io; or the `Cargo.toml` here could be updated to pull from git instead, but I can't see any reason to do that.

**Comment by ids1024** [comment]
I've pushed a commit to call C++ global constructors/destructors, which depends on redox-os/gcc#2. Ideally that would be a separate PR, but since this one rewrites all the C code, that change depends on/conflicts with this one.

**Pull request merged**
